#!/bin/bash

if [[ $EUID -ne 0 ]];
then
	echo "This script must be run as root"
	exit 1
fi

HOMEDIR=$(eval echo "~$(logname)")
(crontab -l ; echo "@reboot ${HOMEDIR}/bin/restore_packages") | crontab -
